//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Chingy_SYSEntities : DbContext
    {
        public Chingy_SYSEntities()
            : base("name=Chingy_SYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Addr_OfficialCity> Addr_OfficialCity { get; set; }
        public DbSet<Addr_OrganizeCity> Addr_OrganizeCity { get; set; }
        public DbSet<DB_RunLog> DB_RunLog { get; set; }
        public DbSet<Dictionary_Column> Dictionary_Column { get; set; }
        public DbSet<Dictionary_Table> Dictionary_Table { get; set; }
        public DbSet<Right_Action> Right_Action { get; set; }
        public DbSet<Right_Assign> Right_Assign { get; set; }
        public DbSet<Right_Controller> Right_Controller { get; set; }
        public DbSet<Right_Module> Right_Module { get; set; }
        public DbSet<UD_DetailView> UD_DetailView { get; set; }
        public DbSet<UD_ModelFields> UD_ModelFields { get; set; }
        public DbSet<UD_Panel> UD_Panel { get; set; }
        public DbSet<UD_Panel_ModelFields> UD_Panel_ModelFields { get; set; }
        public DbSet<UD_Panel_Table> UD_Panel_Table { get; set; }
        public DbSet<UD_Panel_TableRelation> UD_Panel_TableRelation { get; set; }
        public DbSet<UD_TableList> UD_TableList { get; set; }
    }
}
