//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Addr_OfficialCity> Addr_OfficialCity { get; set; }
        public DbSet<Addr_OrganizeCity> Addr_OrganizeCity { get; set; }
        public DbSet<DB_RunLog> DB_RunLog { get; set; }
        public DbSet<Dictionary_Column> Dictionary_Column { get; set; }
        public DbSet<Dictionary_Table> Dictionary_Table { get; set; }
        public DbSet<Right_Action> Right_Action { get; set; }
        public DbSet<Right_Assign> Right_Assign { get; set; }
        public DbSet<Right_Controller> Right_Controller { get; set; }
        public DbSet<Right_Module> Right_Module { get; set; }
        public DbSet<UD_DetailView> UD_DetailView { get; set; }
        public DbSet<UD_ModelFields> UD_ModelFields { get; set; }
        public DbSet<UD_Panel> UD_Panel { get; set; }
        public DbSet<UD_Panel_ModelFields> UD_Panel_ModelFields { get; set; }
        public DbSet<UD_Panel_Table> UD_Panel_Table { get; set; }
        public DbSet<UD_Panel_TableRelation> UD_Panel_TableRelation { get; set; }
        public DbSet<UD_TableList> UD_TableList { get; set; }
    }
}
