//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;

    public partial class Dictionary_Table
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Flag { get; set; }
        public DateTime? InsertTime { get; set; }
        public int? InsertUser { get; set; }
        public DateTime? UpdateTime { get; set; }
        public int? UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
        public string TIMESTAMP { get; set; }

        public virtual ICollection<Dictionary_Column> Dictionary_Column { get; set; }
    }
}
