//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right_Controller
    {
        public Right_Controller()
        {
            this.Right_Action = new HashSet<Right_Action>();
        }
    
        public int ID { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
    
        public virtual ICollection<Right_Action> Right_Action { get; set; }
        public virtual Right_Module Right_Module { get; set; }
    }
}
