//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right_Controller
    {
        public Right_Controller()
        {
            this.Right_Action = new HashSet<Right_Action>();
        }
    
        public int ID { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
    
        public virtual ICollection<Right_Action> Right_Action { get; set; }
        public virtual Right_Module Right_Module { get; set; }
    }
}
