//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_ModelFields
    {
        public UD_ModelFields()
        {
            this.UD_Panel_ModelFields = new HashSet<UD_Panel_ModelFields>();
            this.UD_Panel_TableRelation = new HashSet<UD_Panel_TableRelation>();
            this.UD_Panel_TableRelation1 = new HashSet<UD_Panel_TableRelation>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TableID { get; set; }
        public string FieldName { get; set; }
        public string FieldDisplayName { get; set; }
        public Nullable<int> ColumnSortID { get; set; }
        public string FlagEntity { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> DataLength { get; set; }
        public Nullable<int> Precision { get; set; }
        public string DefaultValue { get; set; }
        public string Description { get; set; }
        public Nullable<int> RelationType { get; set; }
        public string RelationTableName { get; set; }
        public string RelationFieldValue { get; set; }
        public string RelationFieldText { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
    
        public virtual UD_TableList UD_TableList { get; set; }
        public virtual ICollection<UD_Panel_ModelFields> UD_Panel_ModelFields { get; set; }
        public virtual ICollection<UD_Panel_TableRelation> UD_Panel_TableRelation { get; set; }
        public virtual ICollection<UD_Panel_TableRelation> UD_Panel_TableRelation1 { get; set; }
    }
}
