//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_Panel_TableRelation
    {
        public System.Guid ID { get; set; }
        public System.Guid PanelID { get; set; }
        public System.Guid ParentTableID { get; set; }
        public System.Guid ParentFieldID { get; set; }
        public System.Guid ChildTableID { get; set; }
        public Nullable<System.Guid> UD__ID { get; set; }
        public System.Guid ChildFieldID { get; set; }
        public string JoinMode { get; set; }
        public string RelationCondition { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
    
        public virtual UD_ModelFields UD_ModelFields { get; set; }
        public virtual UD_ModelFields UD_ModelFields1 { get; set; }
        public virtual UD_Panel UD_Panel { get; set; }
        public virtual UD_TableList UD_TableList { get; set; }
        public virtual UD_TableList UD_TableList1 { get; set; }
    }
}
