//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_Panel
    {
        public UD_Panel()
        {
            this.UD_Panel_Table = new HashSet<UD_Panel_Table>();
            this.UD_Panel_ModelFields = new HashSet<UD_Panel_ModelFields>();
            this.UD_Panel_TableRelation = new HashSet<UD_Panel_TableRelation>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortID { get; set; }
        public string Enabled { get; set; }
        public string Description { get; set; }
        public int DisplayType { get; set; }
        public Nullable<int> FieldCount { get; set; }
        public string AdvanceFind { get; set; }
        public string DefaultSortFields { get; set; }
        public Nullable<System.Guid> DetailView { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    
        public virtual UD_DetailView UD_DetailView { get; set; }
        public virtual ICollection<UD_Panel_Table> UD_Panel_Table { get; set; }
        public virtual ICollection<UD_Panel_ModelFields> UD_Panel_ModelFields { get; set; }
        public virtual ICollection<UD_Panel_TableRelation> UD_Panel_TableRelation { get; set; }
    }
}
