//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chingy_SYS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_TableList
    {
        public UD_TableList()
        {
            this.UD_ModelFields = new HashSet<UD_ModelFields>();
            this.UD_Panel_Table = new HashSet<UD_Panel_Table>();
            this.UD_Panel_TableRelation = new HashSet<UD_Panel_TableRelation>();
            this.UD_Panel_TableRelation1 = new HashSet<UD_Panel_TableRelation>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string ExtFlag { get; set; }
        public string ModelName { get; set; }
        public string TreeFlag { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public string ExtPropertys { get; set; }
    
        public virtual ICollection<UD_ModelFields> UD_ModelFields { get; set; }
        public virtual ICollection<UD_Panel_Table> UD_Panel_Table { get; set; }
        public virtual ICollection<UD_Panel_TableRelation> UD_Panel_TableRelation { get; set; }
        public virtual ICollection<UD_Panel_TableRelation> UD_Panel_TableRelation1 { get; set; }
    }
}
